### ISSUE TITLE
Support m2e incremental build

### ISSUE THREAD

**Issue by kwin** [awhitford/lombok.maven#15]
Currently if Eclipse is used for a Maven project which leverages lombok, the classes might not contain the generated methods, if Eclipse was building the class (rather than Maven). Would it be possible to provide a lifecycle mapping (http://wiki.eclipse.org/M2E_plugin_execution_not_covered#lifecycle_mapping_metadata_provided_by_maven_plugin) that takes care, that the correct source file is processed (the enriched one) during incremental builds?

**Comment by awhitford** [comment]
I believe I have finally solved this based on guidance found here:  https://wiki.eclipse.org/M2E_compatible_maven_plugins

It is part of **1.16.4.1-SNAPSHOT**.  Is it possible that you can confirm that this is working for you?  (I'd prefer to hear that it works before cutting a release.)

**Comment by awhitford** [comment]
I released version 1.16.4.1.
