### ISSUE TITLE
Incorrect checksum in 1.16.2.0

### ISSUE THREAD

**Issue by kunal546** [awhitford/lombok.maven#16]
Checksum of the dowloaded artifact does not match the checksum in Maven metadata. If you set Maven preference to fail on bad checksums, it'll fail.

This seems like high priority since systems verifying the dependencies with --strict-checksums will fail.

**Comment by awhitford** [comment]
I can see the md5 checksums from [Central](https://repo1.maven.org/maven2/org/projectlombok/lombok-maven-plugin/1.16.2.0/lombok-maven-plugin-1.16.2.0.jar.md5) and I can compare to my local download:

```
MD5 (lombok-maven-plugin-1.16.2.0.jar) = 05015e1ae76608cad2a79b5c3e56e51a
MD5 (lombok-maven-plugin-1.16.2.0.pom) = 27ca7f2c05a944e6931d91ba6e547b65
```

As far as I can tell, they match.

What checksums do you get?  Are you using Artifactory or something?  What version of Maven are you using?  What version of Java?  What OS?

**Comment by awhitford** [comment]
Closing because I can't confirm that it is a legitimate bug.
