### ISSUE TITLE
Cannot find symbol during delombok

### ISSUE THREAD

**Issue by fzakaria** [awhitford/lombok.maven#18]
I am getting `cannot find symbol` during the delombok of the plugin which although seem to benign are confusing. The file gets delombok'd anyways, and the compile phase continues properly however its just unsettling seeing errors in the logs.

The symbols that it is trying to find which are not present exist in transitive dependencies of the maven project being delomboked.

Here is my current setting for the plugin:

``` xml
<plugin>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok-maven-plugin</artifactId>
    <version>1.16.8.0</version>
    <executions>
        <execution>
            <id>default-delombok</id>
            <phase>generate-sources</phase>
            <goals><goal>delombok</goal></goals>
            <configuration>
                <sourceDirectory>src/main-lombok</sourceDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by fzakaria** [comment]
Why would delombok goal even care to try and find the symbols ?
That should be reserved for the compile step ?

**Comment by awhitford** [comment]
@fzakaria I suggest using the main [Project Lombok Discussion](https://groups.google.com/group/project-lombok) since the maven plugin is simply a wrapper for the underlying [Delombok](https://projectlombok.org/features/delombok) feature.

**Comment by pdinc-oss** [comment]
It is approximately line 150 of the AbstractDelombokMojo that is the offender.

```
C:\projects\SNIPPED\DocumentBlock.java:33: error: cannot find symbol
    @Getter(onMethod = @__({ @Id, @GeneratedValue }))
                        ^
  symbol:   class __
  location: class DocumentBlock
```

The code delomboks fine with command line util, and when the setClasspath is not called (commented out).

A pull request is inbound. Please make a release within the week so we do not have to fork and push to central.

**Comment by pdinc-oss** [comment]
any updates?

**Comment by pdinc-oss** [comment]
There is an open Pull Request (https://github.com/awhitford/lombok.maven/pull/36) to fix this issue.

**Comment by awhitford** [comment]
I am unclear on what problem is trying to be solved here.  The original issue from 2016 looks like a usage issue more than a `lombok-maven-plugin` issue.  I do not want to accept a pull request without a documented failure case so that it is absolutely clear what is wrong, and how the proposed fix is resolving it.

If you still think that there is a serious issue to be resolved, please create a new issue with a sample test case to validate the PR.
