### ISSUE TITLE
The documentation is lacking

### ISSUE THREAD

**Issue by o2dac** [awhitford/lombok.maven#20]
It took me hours to make this plugin work, spending lot of time moving back and forth between different pages, only to find out the best information lies in Issues and a google group. Please make the learning process straightforward and documentation helpful by wring a getting started guide and FAQs, and put in in the standard place: Readme.md. (I would write it and make a pull request but some one else would do it better)

**Comment by awhitford** [comment]
You will need to be more specific.  Traditional plugin documentation can be found [here](http://awhitford.github.io/lombok.maven/lombok-maven-plugin/index.html), and there is even a [sample project](http://awhitford.github.io/lombok.maven/test-maven-lombok/index.html) to illustrate how it works.

**Comment by awhitford** [comment]
Added a link to the Plugin Usage to the README.  Hopefully this helps.
