### ISSUE TITLE
'@Setter' does not compile if the field has '@Nullable' annotation also

### ISSUE THREAD

**Issue by balisbalis** [awhitford/lombok.maven#24]
'@Setter' does not compile if the field has '@Nullable' (from com.github.reinert.jjschema) annotation also.

Complation error message is "annotation type not applicable to this kind of declaration"

**Comment by awhitford** [comment]
This sounds like an issue for the _core_ [Project Lombok](https://projectlombok.org/) (rather than something specific to the Maven Plugin). Please record the issue [here](https://github.com/rzwitserloot/lombok/issues).

**Comment by awhitford** [comment]
This does not seem to be an issue with the `lombok-maven-plugin`.
