### ISSUE TITLE
Unable to detect tools.jar (JDK 10)

### ISSUE THREAD

**Issue by getjack** [awhitford/lombok.maven#25]
In lombok-maven-plugin:1.18.0.0:delombok the plugin throws a soft warning stating that the tools.jar cannot be found. This has been removed since JDK 9.

The warning is followed by a more serious warning which may not be a result of this plugin but the lombok project. I don't know what the problem is so i'll post it in this issue.

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by lombok.javac.JavacTreeMaker$TypeTag to method com.sun.tools.javac.code.Type.getTag()
> WARNING: Please consider reporting this to the maintainers of lombok.javac.JavacTreeMaker$TypeTag
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by awhitford** [comment]
I just added [Oracle JDK 10 to the Travis CI](https://docs.travis-ci.com/user/languages/java#using-java-10-and-later) settings, and it appears to be building OK.  Please try the latest versions.

**Comment by Gaibhne** [comment]
I can confirm this happening with OpenJDK 11 for Windows and lombok-maven-plugin:1.18.2.0. Will be happy to help debug.

**Comment by awhitford** [comment]
Issue #27 removes the soft warning about a missing `tools.jar` file when the user is using Java 9 or later.

**Comment by awhitford** [comment]
Do you still have an issue with the latest version?

**Comment by getjack** [comment]
The project i had problems was already abandoned by me. Next time i'll try to write a better reproduction manual. I tried to rebuild it today with OpenJDK 11 and were not able to reproduce this warning.

Case closed for me ;)
