### ISSUE TITLE
java 11 var 

### ISSUE THREAD

**Issue by gavocanov** [awhitford/lombok.maven#28]
Delombok is treating java 11 `var` as lombok `var` and generating code that looks like `        /*missing*/ grouped = blabla.get(id);`

I suppose that just checking for a lombok var import would fix the prob.

**Comment by awhitford** [comment]
This sounds like an issue for the _core_ [Project Lombok](https://projectlombok.org/) (rather than something specific to the Maven Plugin).  Please record the issue [here](https://github.com/rzwitserloot/lombok/issues).

**Comment by awhitford** [comment]
This looks resolved, so closing.
