### ISSUE TITLE
broken link on the plugin page

### ISSUE THREAD

**Issue by SubOptimal** [awhitford/lombok.maven#29]
On the page [About Sample Maven Lombok Projec](https://awhitford.github.io/lombok.maven/test-maven-lombok/index.html) the link to [Cobertura Test Coverage Report](https://awhitford.github.io/lombok.maven/test-maven-lombok/cobertura/org.projectlombok.test.DataExample.html) point to a not existing page.

In commit https://github.com/awhitford/lombok.maven/commit/12a65532 the directory [test-maven-lombok/cobertura](https://github.com/awhitford/lombok.maven/tree/df103f8e62/test-maven-lombok) was removed.

Maybe the directory was removed by purpose, then either the link should be removed or otherwise the link should be fixed to point to the mentioned page.

**Comment by awhitford** [comment]
Good catch!  I had replaced Cobertura with JaCoCo.  Thank you for pointing this out; I will fix it.

**Comment by awhitford** [comment]
Done.  Site will reflect upon next release.
