### ISSUE TITLE
build fails as compiler version from properties is ignored, depends on maven-compiler-plugin

### ISSUE THREAD

**Issue by grexe** [awhitford/lombok.maven#30]
I have tried to build a lombokized project with OpenJDK 11 and it failed, because I have specified the javac version to be used over the shorter properties, which I prefer to including the maven-compiler-plugin just to set it (this way I have it all in one place):
```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>11</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>
```
However, the plugin failed with the well-known error that happens when using an older Lombok or javac version:
```
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
   at java.lang.ClassLoader.findClass (ClassLoader.java:718)
   at java.lang.ClassLoader.loadClass (ClassLoader.java:588)
   at lombok.launch.ShadowClassLoader.loadClass (ShadowClassLoader.java:418)
```
When configuring over the maven-compiler-plugin, it worked.
So the lombok-maven-plugin should evaluate the standard Maven properties for setting the compiler version, too, and not rely on the maven-compiler-plugin.

**Comment by awhitford** [comment]
Are you aware that `${java.version}` is a _built-in_ property?  You can see it with the command:  `mvn help:system` (or by using `mvn help:evaluate`).  As a result, I would not suggest that you _override_ it. 
 I have OpenJDK 11 installed and it's value is `11.0.1`.  Instead, I created a property called `version.java` to avoid the conflict.

However, I am suspicious that something is specifying `<source>` and/or `<target>` in the `maven-compiler-plugin` setup, so your properties may not be leveraged.  This can be validated by leveraging `mvn help:effective-pom`.  Type the command:

```mvn help:effective-pom -Doutput=effpom.xml```

Then, inspect the `effpom.xml` and search for ALL cases of `maven-compiler-plugin` being configured.  Look for any existence of `source` or `target`.

**Comment by awhitford** [comment]
This does not seem to be an issue with the `lombok-maven-plugin`.
