### ISSUE TITLE
Plugin on central repositories

### ISSUE THREAD

**Issue by phcouton** [awhitford/lombok.maven#34]
Version 1.18.8.0 has been published 10 days ago. However, it is not yet available on main repositories such as Maven Central or JCenter. How long does it take to have it available in such repositories ?

Maybe it is available on other repositories ? I don't find one on the plugin site...

**Comment by awhitford** [comment]
Sadly, Pull Request #31 used new Maven 3.6.1 functionality that exposed a break in Sonatype's _Central Sync Requirements_.  I am hoping it will be resolved soon.  You can track what is going on here:  https://issues.sonatype.org/browse/NEXUS-19912

In the meantime, one can use the [version override feature](https://awhitford.github.io/lombok.maven/lombok-maven-plugin/faq.html#version-override) to reference `lombok-1.18.8`, but using `lombok-maven-plugin-1.18.6.0`.

**Comment by phcouton** [comment]
Thanks for the explanation and the workaround!

**Comment by awhitford** [comment]
Version 1.18.8.1 is now available on [central](http://repo1.maven.org/maven2/org/projectlombok/lombok-maven-plugin/1.18.8.1/).
