### ISSUE TITLE
The POM violates the code style. Please format it by running `mvn tidy:pom`.

### ISSUE THREAD

**Issue by pdinc-oss** [awhitford/lombok.maven#37]
The very old check style mojo complains about every pom.xml on initial clone

**Comment by awhitford** [comment]
Why do you feel it is necessary to remove `tidy-maven-plugin`?  It helps ensure some _standards_.

**Comment by awhitford** [comment]
The project is now using the latest `tidy-maven-plugin` (version 1.1.0), and all `pom.xml` are valid.
