### ISSUE TITLE
Does not support Java 16 even when running lombok that does

### ISSUE THREAD

**Issue by md-5** [awhitford/lombok.maven#47]
Lombok added support for Java 16 here: https://github.com/rzwitserloot/lombok/commit/9806e5cca4b449159ad0509dafde81951b8a8523

Even manually adding this version as a depend to the Maven plugin however suffers from the same issue prior to that lombok commit.

```
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.18.0:delombok (default) on project bungeecord-chat: Execution default of goal org.projectlombok:lombok-maven-plugin:1.18.18.0:delombok failed: An API incompatibility was encountered while executing org.projectlombok:lombok-maven-plugin:1.18.18.0:delombok: java.lang.IllegalAccessError: class lombok.delombok.Delombok (in unnamed module @0x1aed255e) cannot access class com.sun.tools.javac.tree.JCTree$JCCompilationUnit (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x1aed255e
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.projectlombok:lombok-maven-plugin:1.18.18.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/user/.m2/repository/org/projectlombok/lombok-maven-plugin/1.18.18.0/lombok-maven-plugin-1.18.18.0.jar
[ERROR] urls[1] = file:/home/user/.m2/repository/org/projectlombok/lombok/edge-SNAPSHOT/lombok-edge-SNAPSHOT.jar
[ERROR] urls[2] = file:/home/user/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[ERROR] urls[3] = file:/home/user/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[4] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```

**Comment by md-5** [comment]
Arguably lombok should be calling `LombokProcessor.addOpensForLombok()` in the Delombok static initializer rather than main

**Comment by md-5** [comment]
Opened PR to lombok

**Comment by awhitford** [comment]
When trying to compile with Java 16, this is what I get:

> Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project lombok-maven-plugin: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x8cc5602) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x8cc5602 -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :lombok-maven-plugin
Error: Process completed with exit code 1.

According to https://github.com/rzwitserloot/lombok/issues/2681, it appears that a Java 16 compatible version of Lombok will be released soon.

**Comment by rzwitserloot** [comment]
@md-5 report an error and then go dig in the jdk16 update to find the culprit? Three cheers to you!

Yup, I'll integrate this. I'm now happy we didn't get around to releasing 1.18.20 on thursday, I'll make sure this fix will make it (via your PR probably :P).

@awhitford - yeah, the edge build already has it, though with an annoyance as md-5 pointed out which I will fix soon. Relase 1.18.20 is imminent. If you can find your way to keep an eye out for a new release this week, that'd be great!

**Comment by md-5** [comment]
Legendary, thanks :)

Closing this as the new lombok version should not need any changes to the Maven plugin

**Comment by ginkel** [comment]
Please pardon my ignorance, but should this be working with the current Lombok edge release? If so, there still seems to be a bug somewhere:

```
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.18.0:delombok (delombok) on project *REDACTED*: Execution delombok of goal org.projectlombok:lombok-maven-plugin:1.18.18.0:delombok failed: An API incompatibility was encountered while executing org.projectlombok:lombok-maven-plugin:1.18.18.0:delombok: java.lang.IllegalAccessError: class lombok.delombok.Delombok (in unnamed module @0x34d480b9) cannot access class com.sun.tools.javac.tree.JCTree$JCCompilationUnit (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x34d480b9
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.projectlombok:lombok-maven-plugin:1.18.18.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/tg/.m2/repository/org/projectlombok/lombok-maven-plugin/1.18.18.0/lombok-maven-plugin-1.18.18.0.jar
[ERROR] urls[1] = file:/home/tg/.m2/repository/org/projectlombok/lombok/edge-SNAPSHOT/lombok-edge-SNAPSHOT.jar
[ERROR] urls[2] = file:/home/tg/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[ERROR] urls[3] = file:/home/tg/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[4] = file:/home/tg/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------

```

Thanks,
Thilo

**Comment by awhitford** [comment]
@ginkel We are waiting on a fresh [Lombok release](https://projectlombok.org/changelog) that supports Java 16.  It sounds like it is imminent.
