### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by jakobbraun** [awhitford/lombok.maven#76]
The website https://awhitford.github.com/lombok.maven/ is currently unreachable.

**Comment by jakobbraun** [comment]
The link above is from the README. Maybe also just that link is incorrect and it should be http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/? In that case don't forget to also update the link in the pom.xml to http://anthonywhitford.com/lombok.maven/

**Comment by awhitford** [comment]
Apparently, it is github.io now:  https://awhitford.github.io/lombok.maven/
I'll update.  Thanks for pointing this out.
